### ISSUE TITLE
Function: Check User Key Validity

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/Tonomy-ID-SDK#124]
Scope:

We need to check if the keys are still valid when the user opens the app each time.

DoD;
Create new function on the UserClass called "checkKeysValid"

- [x] checks the keys in storage match the keys in the blockchain 
- [x] Returns a boolean ValidKeys True/False. 
- [x] Intergration Test - For success case: Keys are Valid and And user excist  
- [x] Intergration Test - For Failure case: Keys are invalid but user excist > Return False
- [x] Intergration Test - For Failure case: Keys are invalid and no user excists >Throw Error

**Comment by kamitor** [comment]
Jack would Appriciate it (but please totally ignore him) that you write teh intergration test first. (Chris also agrees)

**Comment by theblockstalk** [comment]
I made it throw an error instead of returning false
