### ISSUE TITLE
Give a button to External website for the SSO

### ISSUE THREAD

**Issue by Rebal67** [Tonomy-Foundation/Tonomy-ID-SDK#135]
**Description**: 
the external website has a way to add A Tonomy ID login button.
We need to build close to the same functionality of google login button

Reference: https://developers.google.com/identity/sign-in/web/sign-in

DOD:

- [x] Developer gets away to auto import a button with Tonomy Style.
- [x] When the button is clicked the login with tonomy Function is called (onPressLogin)
- [x] Demo app is updated to use the new button of the Login

this is implemented in the demo app 
Reference: https://github.com/Tonomy-Foundation/Tonomy-ID-Demo-market.com/blob/development/src/pages/Home.tsx

**Comment by theblockstalk** [comment]
could use this, but probably not necessary https://unpkg.com/

**Comment by theblockstalk** [comment]
e.g. https://unpkg.com/@tonomy/tonomy-id-sdk@0.3.7/dist/index.js

**Comment by HaseebUllahAbbasi** [comment]
-  Styling and basic event is attached with button
- Some thing Like Google Does,
- file should be min
- file should contains the import from the userApps, js KeyManager,
- the “tsc” directly does not work if import is used in ts file t
- the tsdx configuration does’t work for this problem,it generates the
- the  roll up for changing one file 
   `rollup src/services/externalLogin.ts --file bundle.js --format iife `

- Found the way to bundle in one js file but why to put the whole sdk in file, when we need just one part
- don’t know how to convert just one specific service
  - @theblockstalk  suggestions  
  - find out the way to work with tsdx 
  - use below as an example 
```bash
# To create a new App for SSO
# Call

npx ts-node --project cli.tsconfig.json --transpileOnly id.ts appName username description logoUrl domain publicKey blockchainUrl
```

**Comment by theblockstalk** [comment]
@Rebal67 
> the sdk can also be consumed by clients using script because it is bundled what you really want is 2 entry files and 2 output modules 
```
  "exports": {
    ".": {
      "import": "./dist/es/index.js",
      "require": "./dist/cjs/index.js"
    },
    "./module2": {
      "import": "./dist/es/module2.js",
      "require": "./dist/cjs/module2.js"
    }
  },
  "typesVersions": {
    "": {
      "": [
        "dist/types/index.d.ts"
      ],
      "module2": [
        "dist/types/module2.d.ts"
      ]
    }
  }
```
> this is an example in the package.json

**Comment by theblockstalk** [comment]
looks like this is not well supported in tsdx still. See https://github.com/jaredpalmer/tsdx/issues/175

**Comment by theblockstalk** [comment]
going to try remove dependancy on tsdx. Will need to check the following still works:
- [ ] build
- [ ] unit tests
- [ ] integration tests
- [ ] id.ts scripts
- [ ] bootstrap scripts
- [ ] linting
