### ISSUE TITLE
Publishing SDK

### ISSUE THREAD

**Issue by Rebal67** [Tonomy-Foundation/Tonomy-ID-SDK#136]
**Description**
SDK is published on npm and under the Tonomy Organisation.

DOD:
- [x]  the package name should be updated to '@tonomy/tonomy-id-sdk'
- [x] package should be publicly published
- [x] package must have multiple maintainers  

Hint: 
NP package helps: https://www.npmjs.com/package/np
For reference check:
https://github.com/Tonomy-Foundation/Antelope-SSI-Toolkit/blob/master/package.json

**Comment by theblockstalk** [comment]
checkout https://unpkg.com/
