### ISSUE TITLE
integration tests for the ExternalUser class

### ISSUE THREAD

**Issue by Rebal67** [Tonomy-Foundation/Tonomy-ID-SDK#140]
**Description**
Unit tests are updated for the ExternalUser class and UserApps class
Integration tests are written for the ExternalUser class

- [ ] create integraions tests
   - [x]  loginWithTonomy() then getUser()  (succeeds)
   - [x]  loginWithTonomy() then verifyLogin()  (succeeds)
   - [ ]  loginWithTonomy() then getUser()  (fails: user doesnt exsist on the blockchain)
   - [ ]  loginWithTonomy() then getUser()  (fails: no keys found)
   - [ ]  loginWithTonomy() then getUser()  (fails: User didn't login , keys are found user is found, but keys aren't on blockchain)
   - [ ]  loginWithTonomy() then verifyLogin()  (fails keys aren't valid)
   hint: access JSdom-URL to check urls
   Reference: https://github.com/Tonomy-Foundation/Tonomy-ID-SDK/blob/development/test/app.test.ts
- [x] update unit tests for the login

**Comment by theblockstalk** [comment]
because we have not handled the edge cases where the user doesn't login functionally, i have not implemented the test cases for them either. But if I did I would use scoped jest tests to do this
