### ISSUE TITLE
Message class has internal and external type

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-SDK#153]
Message types to signal how to handle (SDK, Clients) https://github.com/Tonomy-Foundation/Tonomy-ID-SDK/pull/148#discussion_r1123036166

Acceptance criteria:

- [x] the outer "`type` array of strings = `["VerifiableCredential", "TonomyMessage"]. This is used by consumers to determine that it is a Message object
- [x] Message class Stores a property `type` inside the message object (as part of the VC payload). This is used by consumers to tell what type of Message object it is
- [x] Communication.subscribeMessage() takes an optional parameter which allows the subscriber to filter messages by type
- [x] 1x unit test for sign() with type
- [x] 1x integration test for the subscribeMessage() by type
- [ ] update clients

Message class changes:
```ts
static async sign(message: object, issuer: Issuer, type: string, recipient?: string): Promise<Message>
getType(): string
```

Communication class changes:
```ts
subscribeMessage(subscriber: Subscriber, type?: string): void 
```

**Comment by theblockstalk** [comment]
follow up to add to clients

**Comment by theblockstalk** [comment]
three current inner types = request | request confirmation | connection

**Comment by theblockstalk** [comment]
https://github.com/Tonomy-Foundation/Tonomy-ID-SDK/blob/43256bdb349f44f1907b043f7867a7b4ada3a665/src/util/message.ts#L14

**Comment by sadiabbasi** [comment]
const vc: W3CCredential = {
            ..............
            type: ['VerifiableCredential', 'TonomyMessage'],
.......
}
getType(): string {
        return this.decodedJwt.payload.vc.type;
    }

didn't get the communication function changes..

@theblockstalk
