### ISSUE TITLE
User.initializeFromStoage() new function should re-establish connection to server, on app start (SDK, Tonomy ID)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-SDK#155]
Acceptance criteria

- [ ] new async static function `initializeFromStorage()` exists on the user object which will look at the Storage object and see if it can retrieve and initialise a stateful logged-in user object
- [ ] Integration tests for main success and failure cases
- [ ] called in Tonomy ID to initialize on app start

**Comment by sadiabbasi** [comment]
1- create new function in user object i.e. static async initializeFromStorage()
2- check the storage object it if(this.storage);
3- then return idContract.getPerson(this.storage.username);

**Comment by theblockstalk** [comment]
actually, just realized it doesnt need to be static

```ts
class User {
  async intializeFromStorage() {
  if (await this.storage.accountName) 
    check keys are still valid (if they are not, make sure this throws error which i think it already does)
  else
    throw error
  }
}
```

This is called in https://github.com/Tonomy-Foundation/Tonomy-ID/blob/development/src/store/userStore.ts#L45
