### ISSUE TITLE
Subscriber returns a Message object, not string which needs to be turned into Message object (all)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-SDK#156]
Acceptance criteria

- [x] Communication.subScribeMessage() returns a Message object to the subscriber. The function also returns and identify which can be used to unsubscribe.
- [x] integration tests showing this working
- [x] update clients to use new function

**Comment by theblockstalk** [comment]
https://github.com/Tonomy-Foundation/Tonomy-ID-SDK/blob/development/src/communication.ts#L52

**Comment by sadiabbasi** [comment]
subScribeMessage(message: Message, subscriber: Subscriber) {
        this.socketServer.on('message', () => {
            const messageObj = {
                content: message,
                sender: subscriber,
            };

            // emit the message object to the subscriber
            this.socketServer.emit('message', messageObj);
        });
    }

**Comment by Rebal67** [comment]
the message object does have the sender what we meant here is the subscriber function returns a message not a string
