### ISSUE TITLE
Create function to save passphrase words

### ISSUE THREAD

**Issue by sadiabbasi** [Tonomy-Foundation/Tonomy-ID-SDK#291]
Acceptence Criteria:

- [ ] create function that generate private key from passphrase
- [ ] user.savePassphrase that store the private key
- [ ] add integration test to check it generates and save new private key from passphrase
- [ ] update docs if needed

reference: https://github.com/Tonomy-Foundation/Tonomy-ID-SDK/blob/master/src/sdk/controllers/user.ts#L168

**Comment by theblockstalk** [comment]
This function is doing this `options.keyFromPasswordFn(password, salt);` already. What do you want?
